import {
  HiAcademicCap,
  HiCurrencyDollar,
  HiBuildingOffice2,
  HiHome,
  HiPuzzlePiece,
} from 'react-icons/hi2'

// Helper to generate URL-friendly slugs
const slug = (name) =>
  name
    .toLowerCase()
    .replace(/[—–]/g, '-')
    .replace(/[()]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

const makeProject = (name, description, { featured = false, demoUrl = '', githubUrl = '', techStack = [], features = [] } = {}) => ({
  name,
  slug: slug(name),
  description,
  featured,
  demoUrl,
  githubUrl,
  techStack,
  features,
})

export const PORTFOLIO_CATEGORIES = [
  {
    title: 'Education',
    icon: HiAcademicCap,
    subcategories: [
      {
        label: 'Learning Platforms',
        items: [
          makeProject('AI Learning & Training Management System', 'AI-powered platform for managing courses, certifications, and training workflows at scale. Integrates with SSG API for SkillsFuture Singapore ecosystem.', {
            featured: true,
            demoUrl: 'https://ai-lms-tms.vercel.app/',
            githubUrl: 'https://github.com/alfredang/AI-LMS-TMS',
            techStack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Google Gemini', 'SSG API'],
            features: [
              'AI-Powered Learning with Google Gemini chatbot',
              'Course Management (create, edit, manage courses with learning units)',
              'Course Runs & Scheduling with trainer assignments',
              'Enrollment Management with progress tracking',
              'Assessment System with submissions and grading',
              'Certificate Generation on completion',
              'AI-Generated Quizzes based on course content',
              'Personalized Course Recommendations',
              'SSG API Integration for SkillsFuture Singapore',
              'WSQ/IBF Course Support for funded courses',
              'NRIC/FIN Validation for Singapore IDs',
              'Multi-tenant Support for training providers',
              'Trainer Management with certifications',
              'Financial Templates (pro-forma, invoice, receipt, certificate)',
              'Calendar Integration (Google & Microsoft)',
              'Multi-role Support (Learner, Trainer, Admin, Developer, Training Provider)',
              'File Uploads (CV, certificates, profile pictures)',
            ],
          }),
          makeProject('LearnHub', 'AI-powered Learning Management System for personalized and intelligent education workflows with centralized course management and analytics.', {
            featured: true,
            demoUrl: 'https://ai-lms-xi.vercel.app/',
            githubUrl: 'https://github.com/alfredang/ai-lms',
            techStack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'AI'],
            features: [
              'AI-Powered Learning with context-aware chatbot',
              'Gamification (XP points, badges, levels, learning streaks)',
              'Role-Based Access (4 distinct roles with separate dashboards)',
              'Course Enrollment with progress tracking',
              'Dark/Light Mode theme toggle',
              'Responsive Modern UI with Tailwind CSS',
              'Secure Authentication (NextAuth with Google, GitHub OAuth)',
              '7 Course Categories with 21 courses',
              'Course Delivery Formats (Instructor-Led, E-Learning)',
              'Session Types (Classroom, Virtual)',
              'Assignment Submission and Grading',
              'Comprehensive User Guide & Documentation',
              'Multiple AI Provider Support (OpenAI, Gemini, Claude, DeepSeek)',
              'Stripe Payment Processing',
              'PayPal Checkout Support',
              'Superadmin Settings for AI Configuration',
              'API Key Management',
            ],
          }),
          makeProject('Learnify Childcare', 'Corporate e-learning platform for childcare professionals in Singapore with parent engagement tools and Stripe payments.', {
            featured: true,
            demoUrl: 'https://alfredang.github.io/learnify-childcare/',
            githubUrl: 'https://github.com/alfredang/learnify-childcare',
            techStack: ['Next.js 16', 'TypeScript', 'Prisma', 'PostgreSQL', 'Stripe'],
            features: [
              'Multi-tenant Corporate Training Platform',
              'ECDA-Aligned Course Management',
              'SCORM-Compatible Progress Tracking',
              'CPD (Continuing Professional Development) Points',
              'Video Lectures with Progress Tracking',
              'Text-Based Learning Materials',
              'Quiz System with Instant Feedback',
              'Certificate Generation on Completion',
              'Learner Assignment Management',
              'Course Deadline Tracking',
              'Organisation-Scoped Data Isolation',
              'Drag-and-Drop Content Reordering',
              'Rich Text Editor for Course Descriptions',
              'Form Management with Validation',
              'Server State Management',
              'Role-Based Access (Super Admin, Corporate Admin, Learner)',
              'Learner Progress Reports',
            ],
          }),
          makeProject('Lumina Training Management System', 'Enterprise training management with scheduling, compliance tracking, and reporting for organizations.', {
            featured: true,
            githubUrl: 'https://github.com/alfredang/lumina',
            techStack: ['React', 'Node.js', 'MongoDB', 'Tailwind CSS'],
            features: [
              'Multi-Tenant Architecture for training providers',
              'Role-Based Access Control',
              'Course Management with topics and subtopics',
              'Class Scheduling with trainer assignments',
              'Smart Enrollment with fee calculations',
              'Payment Processing via Stripe',
              'Singapore Funding Support (SSG, SkillsFuture Credit, PSEA, MCES, UTAP, IBF)',
              'AI-Powered Learning with Gemini integration',
              'Progress Tracking and Assessment Results',
              'Automated Fee Calculations with funding deductions',
              'Learner Enrollment System',
              'Class Management',
              'Training Provider Dashboard',
              'Separate Frontend and Backend (Vite + Express)',
              'Serverless Postgres with Neon',
            ],
          }),
          makeProject('Learnify', 'Modern online learning marketplace with course creation, video streaming, Stripe payments, and role-based access for students, instructors, and admins.', {
            demoUrl: 'https://learnify-corporate-training-platform.netlify.app/',
            githubUrl: 'https://github.com/alfredang/Learnify',
            techStack: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Stripe'],
            features: [
              'Browse and search courses with smart filters',
              'Shopping cart system for course purchases',
              'Video content viewing with ratings and reviews',
              'Course bookmarking and completion certificates',
              'Instructor course creation with multimedia support',
              'Flexible pricing models for courses',
              'Instructor analytics and earnings tracking (70% revenue share)',
              'Admin dashboards with user management',
              'Course approval workflows',
              'Category administration with custom icons',
              'Drag-and-drop lecture reordering',
              'Rich text editing for course descriptions',
              'Automated certificate generation',
              'Role-based access control (student, instructor, admin)',
              'OAuth authentication support',
            ],
          }),
        ],
      },
      {
        label: 'Kids & Interactive',
        items: [
          makeProject('Educational Escape Rooms', 'Interactive browser-based educational escape rooms teaching AI, data, ethics, sustainability & coding through 5 themed rooms with 15+ puzzles.', {
            demoUrl: 'https://alfredang.github.io/escaperooms/',
            githubUrl: 'https://github.com/alfredang/escaperooms',
            techStack: ['HTML5', 'CSS3', 'JavaScript'],
            features: [
              '5 themed rooms (Space Operations, Food Systems, Ethics, Green Tech, Cyber City)',
              '15+ unique puzzles (flowcharts, dashboards, decision trees, crosswords, simulations)',
              'Meta puzzle finale combining artifacts from all rooms',
              'AI-powered hints with OpenAI and Anthropic support',
              'Socratic questioning for hint delivery',
              'Synthesized audio via Web Audio API',
              'Auto-save functionality with browser storage',
              'Responsive design for desktop, tablet, and mobile',
              'Achievement system with badges',
              'Dynamic theming for each room',
              'Keyboard navigation accessibility',
              'Vanilla JavaScript implementation',
            ],
          }),
          makeProject('Musical Timer Countdown', 'Polished, distraction-free countdown timer for classes, study blocks, and focused breaks with sound previews and looping alarm tracks.', {
            demoUrl: 'https://alfredang.github.io/musical-timer-countdown/',
            githubUrl: 'https://github.com/alfredang/musical-timer-countdown',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              'Preset times (15m, 30m, 45m, 1h, 1h 15m, 1h 30m)',
              'Manual time input option',
              'Animated progress ring',
              'Pause/resume functionality',
              'Reset function',
              'Three built-in alarm options',
              'Custom MP3 upload (up to 5MB)',
              'Adjustable volume slider',
              'Sound preview testing',
              'Six color themes',
              'Browser localStorage for preference saving',
              'Fully responsive design',
              'Vanilla HTML5, CSS3, and JavaScript',
            ],
          }),
          makeProject('Phonics AI', 'Interactive phonics learning app for ages 9-15 with games, AI features, and gamification powered by Gemini AI.', {
            demoUrl: 'https://alfredang.github.io/phonics-ai/',
            githubUrl: 'https://github.com/alfredang/phonics-ai',
            techStack: ['Next.js', 'Firebase', 'Google Gemini'],
            features: [
              '5 learning worlds with progressive curriculum',
              '44 phonemes with complete English sound coverage',
              '95 structured lessons following four-phase approach',
              'Google Gemini API for pronunciation analysis',
              'Web Speech API for voice recording and text-to-speech',
              'Six interactive game types (Phoneme Pop, Word Builder, Sound Match, Sound Race, Sentence Scramble, Karaoke Challenge)',
              'XP and level progression system',
              '18 achievement badges',
              'Daily quests with bonus rewards',
              'Streak tracking for engagement',
              'Visual intonation markers (rising/falling/sustained arrows)',
              'Karaoke-style text highlighting',
              'AI feedback on pronunciation, fluency, and intonation',
              'Progress tracking dashboard',
              'Customizable settings for audio and gameplay',
            ],
          }),
          makeProject('PhonixQuest', 'Vibrant, AI-powered phonics learning adventure for kids. Master sounds, blending, and pronunciation with real-time feedback from Google Gemini.', {
            demoUrl: 'https://alfredang.github.io/PhonixQuest/',
            githubUrl: 'https://github.com/alfredang/PhonixQuest',
            techStack: ['HTML5', 'CSS3', 'JavaScript', 'Google Gemini'],
            features: [
              'Gamified learning progression with adventure map system',
              'Level unlocking based on phonetic mastery',
              'Google Gemini AI for voice feedback',
              'Interactive educational games (Pop the Phoneme, Build the Word)',
              'Experience points collection system',
              'Star rewards system',
              'Learning streak building',
              'Five progressive learning levels (phonemes, blending, phonics rules, sentence reading, story comprehension)',
              'Beautiful responsive design',
              'Tailwind CSS 4 styling',
              'Framer Motion smooth animations',
            ],
          }),
        ],
      },
      {
        label: 'Tutorials',
        items: [
          makeProject('WSQ Courseware Generator', 'AI-powered WSQ courseware generation platform built with Claude Agent SDK and Streamlit. Automates creation of Assessment Plans, Facilitator Guides, Learner Guides, Lesson Plans, Assessments, Slides, and Brochures.', {
            githubUrl: 'https://github.com/alfredang/wsq-courseware-generator-claude-streamlit',
            techStack: ['Python', 'Claude Agent SDK', 'Streamlit', 'NotebookLM'],
            features: [
              'Automated Assessment Plan generation',
              'Facilitator Guide creation',
              'Learner Guide generation',
              'Lesson Plan development',
              'Assessment creation with rubrics',
              'Slide deck generation',
              'Course brochure design',
              'Claude Agent SDK integration',
              'NotebookLM API for content research',
              'Streamlit web interface',
              'WSQ compliance for Singapore training providers',
              'Batch courseware generation',
              'Customizable templates',
              'AI-powered content quality checks',
            ],
          }),
          makeProject('Course Helper (SEO & Content)', 'Streamlit dashboard that uses Claude CLI to generate SEO content, AI image prompts, and newsletters for WSQ and non-WSQ courses.', {
            githubUrl: 'https://github.com/alfredang/course-helper',
            techStack: ['Python', 'Streamlit', 'Claude AI', 'SEO'],
            features: [
              'SEO content generation for courses',
              'AI-powered course descriptions',
              'Newsletter content creation',
              'AI image prompt generation',
              'WSQ course content optimization',
              'Non-WSQ course support',
              'Claude CLI integration',
              'Streamlit dashboard interface',
              'Batch content generation',
              'Marketing copy creation',
              'Course metadata optimization',
              'Content export functionality',
            ],
          }),
          makeProject('WSQ/CASL Course Proposal Generator', 'Web app to prepare and submit WSQ and CASL Course Proposals (CP) to SSG TPG, powered by Claude Code content generation and Streamlit UI.', {
            githubUrl: 'https://github.com/alfredang/wsq-casl-cp-generator',
            techStack: ['Python', 'Streamlit', 'Claude AI'],
            features: [
              'WSQ Course Proposal generation',
              'CASL Course Proposal generation',
              'SSG TPG submission format compliance',
              'Claude Code AI-powered content generation',
              'Streamlit user interface',
              'Course outline creation',
              'Learning outcomes development',
              'Assessment criteria generation',
              'Training provider details integration',
              'Automated proposal formatting',
              'Export to submission-ready format',
              'Template-based proposal structure',
            ],
          }),
          makeProject('SSG API Portal', 'Developer tool for exploring SkillsFuture Singapore (SSG-WSG) APIs. Course lookup, search by UEN/keyword, mTLS + OAuth authentication.', {
            githubUrl: 'https://github.com/alfredang/ssg-api-portal',
            techStack: ['React', 'TypeScript', 'Express', 'Vite'],
            features: [
              'SkillsFuture Singapore (SSG-WSG) API integration',
              'Course lookup and search functionality',
              'Search by UEN (Unique Entity Number)',
              'Keyword-based course search',
              'mTLS (mutual TLS) authentication',
              'OAuth 2.0 authentication flow',
              'React + TypeScript frontend',
              'Express backend server',
              'Vite build tooling',
              'API endpoint testing',
              'Developer-friendly interface',
              'Real-time API response viewing',
            ],
          }),
          makeProject('AutoGen AI Agents Tutorial', 'Hands-on tutorial for building AI agents with Microsoft AutoGen — covering single agents, tools, multi-agent teams, and human-in-the-loop workflows.', {
            githubUrl: 'https://github.com/alfredang/autogen_tutorial',
            techStack: ['Python', 'AutoGen', 'OpenAI'],
            features: [
              'Single agent development with OpenAI GPT models',
              'Custom tool integration for web search and API calls',
              'Multi-agent teams with RoundRobinGroupChat',
              'Human-in-the-loop workflows with UserProxyAgent',
              'Async programming with Python asyncio',
              'Jupyter notebook with comprehensive examples',
              'Standalone Python scripts for specific workflows',
              'Web search integration via Tavily',
              'Configuration guidance for API integrations',
              'Python 3.11+ support',
            ],
          }),
          makeProject('Google ADK Tutorial', 'Collection of example AI agents built with Google Agent Development Kit (ADK) featuring multi-agent systems, tool integration, and various LLM providers.', {
            githubUrl: 'https://github.com/alfredang/gemini-adk-tutorial',
            techStack: ['Python', 'Google ADK', 'LLM'],
            features: [
              'Multiple agent architectures (basic LLM, sequential, parallel, loop agents)',
              'Hierarchical multi-agent system for stock analysis',
              'Travel planning system with specialized sub-agents',
              'Itinerary creation agents',
              'Budget estimation agents',
              'Cultural guidance agents',
              'Gemini models as default',
              'Alternative provider integration (OpenAI, Claude via LiteLlm)',
              'Google Search tool integration',
              'Custom function-based tools',
              'Stock agent for equity analysis',
              'Travel agent for trip planning',
              'Tutor agent for subject-specific education',
              'Python 3.13+ support',
              'Session management with InMemorySessionService',
            ],
          }),
          makeProject('Langflow & Streamlit Tutorial', 'Learn to build AI workflows with Langflow and deploy interactive apps with Streamlit.', {
            githubUrl: 'https://github.com/alfredang/Langflow-and-Streamlit-Tutorial',
            techStack: ['Python', 'Langflow', 'Streamlit'],
            features: [
              'Langflow visual workflow builder integration',
              'Drag-and-drop AI workflow design',
              'Streamlit web application development',
              'Interactive UI components',
              'LLM testing and experimentation',
              'Agent implementations and orchestration',
              'API integration with Langflow',
              'Real-time chat interfaces',
              'Python-based tutorial structure with examples',
              'Hands-on code samples',
              'Deployment instructions',
              'Best practices for AI workflow design',
            ],
          }),
        ],
      },
    ],
  },
  {
    title: 'Finance & Productivity',
    icon: HiCurrencyDollar,
    subcategories: [
      {
        label: 'Financial Tools',
        items: [
          makeProject('Algorithmic Trading Dashboard', 'Automated algorithmic trading dashboard with Gemini 2.0 AI insights, multi-strategy backtesting, and performance comparison.', {
            githubUrl: 'https://github.com/alfredang/algorithmic-trading',
            techStack: ['Python', 'Streamlit', 'Gemini AI', 'yfinance'],
            features: [
              'Multiple trading strategies (Moving Average, RSI, MACD, Bollinger Bands)',
              'Multi-strategy backtesting engine',
              'Historical data analysis with yfinance',
              'Performance metrics comparison',
              'Gemini 2.0 AI-powered trading insights',
              'AI analysis of trading patterns',
              'Interactive Streamlit dashboard',
              'Real-time strategy performance tracking',
              'Portfolio optimization recommendations',
              'Risk analysis and reporting',
              'Customizable strategy parameters',
              'Visualization of backtesting results',
              'Trade signal generation',
              'Quantitative finance analytics',
            ],
          }),
          makeProject('Value Investment Academy', 'AI-powered value investing tool with stock screening, financial anomaly detection (M-Score, Z-Score, F-Score), and automated investment report generation for US & Singapore markets.', {
            featured: true,
            demoUrl: 'https://value-investment-academy.streamlit.app/',
            githubUrl: 'https://github.com/alfredang/value-investment',
            techStack: ['Python', 'Streamlit', 'AI', 'Finance APIs'],
            features: [
              'Stock Screener with 10 filtering criteria',
              'Profitability Metrics (Gross Margin, Net Margin, ROA, ROE, FCF Margin)',
              'Growth Metrics (5-Year Revenue and EPS Growth)',
              'Efficiency Metrics (ROIC, ROTE vs WACC)',
              'Balance Sheet Analysis (Debt-to-Equity)',
              'Multi-Exchange Support (NASDAQ, NYSE, SGX)',
              'Multi-File Upload for US and SG stocks',
              'Automated Valuation using EPV (Earnings Power Value)',
              'Valuation Classifications (Undervalued, Fair Value, Overvalued)',
              'AI Anomaly Detection using OpenAI',
              '10-Year Financial History Analysis',
              'Financial Anomaly Ratings (CLEAN, MINOR, MATERIAL)',
              'Professional Summary Report Dashboard',
              'Executive Summary with KPI cards',
              'Portfolio Analytics with interactive charts',
              'Radar Charts for metric comparison',
              'Valuation Scatter Plot',
              'Company Deep Dive Cards with color coding',
              'Conviction Scoring (0-100)',
              'DOCX Report Export',
              'AI Agent Team with specialized roles',
              'Real-Time Data Integration (FMP, Tavily, NewsAPI)',
              'Web Search capabilities',
              'Financial Modeling Prep API integration',
              'Command Line Interface',
            ],
          }),
          makeProject('Stock Analysis Telegram Agent', 'Autonomous multi-agent system delivering real-time stock trade recommendations via Telegram with technical analysis, market sentiment, and AI decision-making.', {
            githubUrl: 'https://github.com/alfredang/stock_analysis_telegram_agent',
            techStack: ['Python', 'Telegram API', 'Multi-Agent AI'],
            features: [
              'Multi-agent autonomous trading analysis platform',
              'Multi-timeframe data fetching (1-minute, 15-minute, 1-hour intervals)',
              'OHLCV data analysis (Open, High, Low, Close, Volume)',
              'Trend confirmation using hourly candles',
              'Real-time news integration via NewsAPI',
              'Automated sentiment classification (Positive, Neutral, Negative)',
              'Numerical sentiment scoring (-1 to 1)',
              'Buy/Sell/Hold signal generation',
              'Specific entry price points',
              'Stop-loss level calculation',
              'Target price projections',
              'Detailed trade rationales',
              'Chain of Thought methodology',
              'SentimentAnalyzer agent',
              'TradeDecisionAgent orchestration',
              'Telegram delivery of recommendations',
            ],
          }),
        ],
      },
      {
        label: 'Productivity Tools',
        items: [
          makeProject('Markdown To PDF Converter', 'Chrome extension to convert Markdown to beautifully styled PDF with live preview.', {
            githubUrl: 'https://github.com/alfredang/md2pdf-chrome-extension',
            techStack: ['JavaScript', 'Chrome Extension API'],
            features: [
              'Live markdown preview',
              'GitHub-style styling',
              'Split-pane interface',
              'Custom PDF filenames',
              'GitHub Flavored Markdown support',
              'Tables and task lists support',
              'Code blocks and blockquotes',
              'A4 PDF output with margins',
              'Real-time rendering as you type',
              'marked.js for markdown parsing',
              'html2pdf.js for PDF generation',
              'Manifest V3 Chrome extension framework',
            ],
          }),
          makeProject('Rich Text To Markdown Converter', 'Chrome extension to convert rich text to GitHub Flavored Markdown. Paste from Word, Google Docs, or any webpage and get clean markdown instantly.', {
            githubUrl: 'https://github.com/alfredang/md-converter-chrome-extension',
            techStack: ['JavaScript', 'Chrome Extension API'],
            features: [
              'Auto-convert on paste functionality',
              'GitHub Flavored Markdown support',
              'Tables handling',
              'Strikethrough formatting',
              'Task lists support',
              'One-click copy to clipboard',
              'Clean output without unnecessary blank lines',
              'Rich text conversion from Word documents',
              'Google Docs conversion support',
              'Web content conversion',
            ],
          }),
          makeProject('Strong Password Generator (MCP)', 'MCP server for generating cryptographically secure passwords with customizable rules, strength analysis, and passphrase generation.', {
            githubUrl: 'https://github.com/alfredang/strong-password-generator-mcp',
            techStack: ['Python', 'FastMCP 2.0'],
            features: [
              'Cryptographically secure password generation',
              'Customizable password length (8-128 characters)',
              'Symbol inclusion/exclusion option',
              'Numbers inclusion/exclusion option',
              'Mixed case configuration',
              'Ambiguous character filtering (0, O, l, 1, I)',
              'Entropy calculations',
              'Security ratings for password strength',
              'Passphrase generation alternative',
              'Single password generation',
              'Batch generation (1-20 at once)',
              'Password strength checking',
              'Model Context Protocol integration with Claude Desktop',
            ],
          }),
          makeProject('Word/PPT To PDF Converter', 'Chrome extension to convert Word (.docx) and PowerPoint (.pptx) documents to PDF.', {
            githubUrl: 'https://github.com/alfredang/pdf-converter-chrome-extension',
            techStack: ['JavaScript', 'Chrome Extension API'],
            features: [
              'Word (.docx) to PDF conversion',
              'PowerPoint (.pptx) to PDF conversion',
              'Drag-and-drop file upload',
              'Click-to-browse file selection',
              'Automatic PDF download',
              'One-click conversion button',
              'Chrome Extension (Manifest V3) UI',
              'Python backend with Starlette and Uvicorn',
              'LibreOffice headless mode processing',
              '/health endpoint for status checks',
              '/convert POST endpoint for conversion',
              'Multipart form data handling',
            ],
          }),
        ],
      },
    ],
  },
  {
    title: 'HR & Technology',
    icon: HiBuildingOffice2,
    subcategories: [
      {
        label: 'HR Systems',
        items: [
          makeProject('AI HR Management System', 'AI-powered HR platform with employee management, leave tracking, Singapore CPF payroll, expense claims, and Gemini chatbot.', {
            featured: true,
            demoUrl: 'https://ai-hrm.vercel.app/',
            githubUrl: 'https://github.com/alfredang/ai-hrms',
            techStack: ['Next.js 14', 'TypeScript', 'Prisma', 'Neon Postgres', 'Google Gemini'],
            features: [
              'Real-time HR Dashboard with pending approvals',
              'Complete Staff Directory with search and filters',
              'Grid and List View Options',
              'Multiple Leave Types (Annual, Sick, Medical, Compassionate)',
              'Leave Balance Tracking per employee per year',
              'Leave Request Approval Workflow with email notifications',
              'Payroll with Singapore CPF Calculations',
              'Age-Based CPF Rate Adjustments',
              'Monthly Payslip Generation with PDF download',
              'Salary Configuration per employee',
              'Expense Claims with receipt uploads',
              'Expense Approval Workflow',
              'Full Calendar with event management',
              'Color-Coded Event Types (Holidays, Meetings, Training, Company Events, Leave)',
              'AI Chatbot powered by Google Gemini',
              'Context-Aware HR Policy Responses',
              'Manager Assignment and Org Hierarchy',
              'Role-Based Access Control (Staff, Manager, HR, Admin)',
              'Payment Status Tracking',
              'Floating Chat Widget',
            ],
          }),
          makeProject('Tertiary HRMS (Cross-Platform)', 'Cross-platform HRMS application for Web, iOS, and Android with payroll, leave management, and PWA capabilities using Capacitor.', {
            githubUrl: 'https://github.com/alfredang/tertiary-hrms',
            techStack: ['Next.js', 'TypeScript', 'Prisma', 'Capacitor', 'Tailwind CSS'],
            features: [
              'Cross-platform deployment (Web, iOS, Android)',
              'Progressive Web App (PWA) support',
              'Capacitor for native mobile features',
              'Employee management system',
              'Leave tracking and approvals',
              'Payroll processing',
              'Expense claims management',
              'AI-powered HR chatbot',
              'Mobile-first responsive design',
              'Native app installation',
              'Offline capabilities',
              'Push notifications support',
              'TypeScript for type safety',
              'Tailwind CSS for styling',
            ],
          }),
        ],
      },
      {
        label: 'Enterprise Tools',
        items: [
          makeProject('NotebookLM MCP Bridge', 'Bridge connecting Google NotebookLM with Claude via MCP for full programmatic access to create notebooks, manage sources, and generate AI-powered content.', {
            githubUrl: 'https://github.com/alfredang/notebooklm-mcp',
            techStack: ['Python', 'MCP', 'NotebookLM API'],
            features: [
              'Research management (list and create notebooks)',
              'Content integration (add URLs, text, and files as sources)',
              'Podcast generation',
              'Video generation',
              'Slides generation',
              'Mind maps generation',
              'Infographics generation',
              'Quiz generation',
              'Flashcards generation',
              'Report generation',
              'Natural chat interaction with sources',
              "Claude's reasoning integration",
              '14 callable functions',
              'NotebookLM authentication',
              'notebooklm-py client library',
              'fastmcp framework support',
            ],
          }),
          makeProject('Tertiary Infotech Voice Agent', 'AI voice agent landing page for automated customer support and real-time voice calls, powered by Retell.io.', {
            demoUrl: 'https://tertiary-voiceagent.vercel.app/',
            githubUrl: 'https://github.com/alfredang/voiceagent',
            techStack: ['React', 'Retell.io', 'Vercel'],
            features: [
              'Real-time browser-based voice conversations',
              'Retell Web Client SDK integration',
              'Text-based chat functionality',
              'Embedded Retell chat popup',
              'Interactive call interface with speaking indicators',
              'Call timer display',
              'Visual ripple effects during conversations',
              'Mobile optimization and responsive design',
              'Secure backend via Vercel serverless functions',
              'API key protection (never exposed to client)',
              'Express server for local development',
              'Inter typography',
            ],
          }),
        ],
      },
      {
        label: 'AI Creative Tools',
        items: [
          makeProject('Content Creators (CrewAI)', 'Multi-agent AI content generation system using CrewAI with Streamlit interface. Research, write, and edit professional articles automatically.', {
            demoUrl: 'https://content-creators.streamlit.app/',
            githubUrl: 'https://github.com/alfredang/content-creators-crewai',
            techStack: ['Python', 'CrewAI', 'Streamlit'],
            features: [
              'Hierarchical multi-agent team',
              'Content Director agent for task coordination',
              'Research Specialist agent with web search',
              'Content Writer agent for article composition',
              'Content Editor agent for quality checks',
              'Five-phase operational workflow',
              'User topic submission interface',
              'Research gathering capability',
              'Article composition and formatting',
              'Editorial review system',
              'Markdown output generation',
              'Streamlit web application interface',
              'Real-time status monitoring',
              'Command-line interface option',
              'CrewAI framework integration',
              'OpenAI language models',
              'Tavily search capabilities',
              'Python 3.10-3.13 support',
            ],
          }),
          makeProject('Groovy Dance Studio', 'AI-powered creative studio for dance generation, image creation/editing, media analysis, and intelligent chat powered by Google Gemini.', {
            demoUrl: 'https://groovydance-app.netlify.app/',
            githubUrl: 'https://github.com/alfredang/groovydance',
            techStack: ['React', 'Google Gemini', 'Netlify'],
            features: [
              'Dance generator for transforming photos into dancing characters',
              'Photo upload capability',
              'Dance move description input',
              'Video reference link pasting',
              'Background music addition',
              'Dance preview generation',
              'Image studio for text-to-image creation',
              'Image modification with natural language instructions',
              'Analysis lab for media file questions',
              'AI-generated insights and descriptions',
              'AI Assistant with web search integration',
              'Cited sources for information',
              'React 19 with TypeScript',
              'Tailwind CSS styling',
              'Google Gemini API integration',
              'Netlify deployment',
              'Serverless backend functions',
            ],
          }),
          makeProject('Idea Galaxy', 'Space-themed idea visualization platform where ideas appear as glowing stars. Create, connect, and evolve ideas with AI-powered discovery.', {
            demoUrl: 'https://idea-galaxy.netlify.app/',
            githubUrl: 'https://github.com/alfredang/idea-galaxy',
            techStack: ['React', 'FastAPI', 'MongoDB'],
            features: [
              'Interactive galaxy canvas visualization',
              'Ideas represented as glowing stars with colors and sizes',
              'Multiple status options (spark, developing, refined, completed, archived)',
              'Idea creation, editing, and deletion',
              'Constellation links for connecting related ideas',
              'Visual constellation line connections',
              'AI-powered idea discovery',
              'Keyword-based similarity matching',
              'Public galaxy sharing via links',
              'Responsive design for desktop and mobile',
            ],
          }),
        ],
      },
      {
        label: 'Advanced Tech',
        items: [
          makeProject('LeRobot — AI Robotics', 'Robotics project integrating LeRobot framework with ChatGPT-4o Vision API for intelligent control of a LeKiwi mobile manipulator.', {
            githubUrl: 'https://github.com/alfredang/lerobot',
            techStack: ['Python', 'LeRobot', 'ROS2', 'GPT-4o Vision'],
            features: [
              'Manual teleoperation with leader-follower arm control',
              'Vision-only autonomous mode with ChatGPT-4o Vision API',
              'SLAM-enabled autonomous navigation',
              'Dual camera feeds (front-facing and wrist-mounted)',
              'RPLidar A1 for 360° laser scanning',
              'Jetson Orin Nano 8GB for onboard processing',
              '6-DOF arm manipulation',
              '3-wheel omnidirectional base movement',
              'Real-time motor control and sensor processing',
              'Scene understanding from camera analysis',
              'Natural language task planning',
              'Autonomous object detection and grasping',
              'Multi-object pick-and-place operations',
              'ZMQ motor command communication',
              'HTTP REST for camera streaming',
              'SLAM data communication over HTTP',
            ],
          }),
        ],
      },
    ],
  },
  {
    title: 'Real Estate & Lifestyle',
    icon: HiHome,
    subcategories: [
      {
        label: 'Property',
        items: [
          makeProject('Property Finder', 'Full-stack PropertyGuru Singapore clone with property search, filters, SSR pages, user auth, favorites, and 120+ sample listings.', {
            featured: true,
            demoUrl: 'https://propertyguruking.netlify.app/',
            githubUrl: 'https://github.com/alfredang/propertyfinder',
            techStack: ['Next.js 14', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
            features: [
              'Advanced Property Search with multiple filters',
              'Location-Based Filtering',
              'Price Range Filtering',
              'Property Type Filtering',
              'Bedroom and Bathroom Filtering',
              'Grid and List View Options',
              'Property Cards with key details',
              'Comprehensive Property Detail Pages',
              'Image Gallery for properties',
              'Amenities Display',
              'Nearby Places Information',
              'Agent Information Display',
              'User Authentication (Email/Password & Google OAuth)',
              'Favorites/Watchlist Feature',
              'Admin Panel for property management',
              'User Management',
              'Agent Management',
              'Responsive Mobile-First Design',
              'SEO Optimization with server-side rendering',
              'Structured Data Implementation',
              'Mapbox GL JS Integration',
              'Cloudinary Image Management',
              'NextAuth.js authentication',
              'React Query for state management',
              '120+ seed properties',
            ],
          }),
          makeProject('Property Advisor', 'Intelligent property advisory tool with market analysis, property discovery, and management features.', {
            demoUrl: 'https://propertyadvisor-frontend.vercel.app/',
            githubUrl: 'https://github.com/alfredang/propertyadvisor',
            techStack: ['React', 'Node.js', 'Vercel'],
            features: [
              'Modern responsive UI with Next.js 14',
              'Advanced property search by location, price, and type',
              'Detailed property pages with image galleries',
              'Personal watchlist management',
              'RESTful API with Node.js & Express',
              'JWT-based secure authentication',
              'Role-based access control (admin and users)',
              'Over 100 sample properties in database',
              'Server-side rendering (SSR)',
              'Image optimization',
              'PostgreSQL integration with Neon',
              'Prisma ORM for type-safe database operations',
              'Mobile-first responsive design',
              'Sitemap and robots.txt for SEO',
              'Social sharing meta tags',
              'Vercel deployment',
              'Docker support for local development',
            ],
          }),
        ],
      },
      {
        label: 'Travel & Lifestyle',
        items: [
          makeProject('Recycle & Resell', 'Carousell-style marketplace for buying and selling second-hand items, promoting sustainability.', {
            featured: true,
            demoUrl: 'https://recycle-resell.netlify.app/',
            githubUrl: 'https://github.com/alfredang/recycle-resell',
            techStack: ['Next.js', 'Prisma', 'Netlify'],
            features: [
              'User Authentication with email/password or Google OAuth',
              'Listing Management (create, edit, delete listings)',
              'Multiple Image Uploads per listing',
              'Advanced Search with filters',
              'Category Filtering',
              'Price Range Filtering',
              'Condition Filtering',
              'Location-Based Filtering',
              'Favorites/Watchlist System',
              'Real-time Chat between users',
              'Offer System for price negotiation',
              'User Reviews and Ratings',
              'Transaction Trust Building',
              'Responsive Mobile-First Design',
              'Bottom Navigation for Mobile',
              'Carousell-Style Marketplace',
              'Vercel Blob Storage for images',
              'Pusher for real-time messaging',
              'NextAuth.js v5 authentication',
              'Prisma ORM for database management',
              'Neon Serverless PostgreSQL',
              'Complete Documentation on GitHub Pages',
            ],
          }),
          makeProject('AI Trip Advisor', 'Interactive AI-driven trip planning app with multi-agent orchestration generating personalized travel itineraries based on user preferences.', {
            demoUrl: 'https://trip-advisor-openrouter.streamlit.app/',
            githubUrl: 'https://github.com/alfredang/trip-advisor',
            techStack: ['Python', 'Streamlit', 'Multi-Agent AI'],
            features: [
              'Interactive user interface for destination input',
              'Trip duration customization',
              'Budget specification',
              'Special preferences configuration',
              'Multi-agent architecture (Planning, Budget, Local Guide, Research agents)',
              'Day-by-day itinerary generation',
              'Budget breakdown and tracking',
              'Local dining suggestions',
              'Travel updates and current information',
              'Downloadable trip plans',
              'Streamlit web application interface',
              'OpenAI Agents SDK orchestration',
              'Gemini 2.5 Flash Lite language model',
              'Tavily real-time web search integration',
              'Personalized recommendations based on preferences',
            ],
          }),
          makeProject('EV Charging Points Singapore', 'Interactive map of EV charging points in Singapore with real-time availability from LTA DataMall API.', {
            demoUrl: 'https://ev-charging-points-sg.vercel.app',
            githubUrl: 'https://github.com/alfredang/ev-charging-points-sg',
            techStack: ['Next.js', 'LTA DataMall API', 'Vercel'],
            features: [
              'Interactive Google Maps integration',
              'Custom teardrop markers for charging points',
              'Real-time data from LTA DataMall Batch API',
              'Automatic user location detection',
              'Distance-based sorting of charging points',
              'Color-coded availability (green/orange/red/gray)',
              'Search by location name, postal code, or company',
              'Filter capabilities',
              'Responsive design for desktop and mobile',
              'Interactive sidebar with map panning',
              'Detailed information windows for stations',
              'HTML5, CSS3, Vanilla JavaScript implementation',
              'Vercel serverless functions',
            ],
          }),
          makeProject('Hiking Advisor', 'Modern hiking trail finder with interactive maps, real-time weather, and an AI-powered assistant.', {
            demoUrl: 'https://hiking-advisor.netlify.app/',
            githubUrl: 'https://github.com/alfredang/hiking-advisor',
            techStack: ['Next.js 14', 'TypeScript', 'Google Gemini', 'Netlify'],
            features: [
              'Interactive trail mapping with Google Maps',
              'Trail markers and polyline paths',
              'User location tracking',
              'Smart filtering by difficulty, distance, elevation, path type, and amenities',
              'Real-time weather integration',
              'Suitability ratings (good/caution/unsafe)',
              'Google Gemini AI-powered trail recommendations',
              'Chat interface for personalized suggestions',
              'Comprehensive trail statistics and information',
              'Facility details and safety guidance',
              'Visitor ratings and reviews',
              'Photo gallery from Google Places API',
              'Bookmarked favorites with browser storage persistence',
              'Responsive design with dark mode support',
              'Metric/imperial unit toggling',
              'Targeting Singapore and Malaysia trails',
            ],
          }),
          makeProject('Potluck', 'Marketplace platform connecting home chefs with food lovers in Singapore. Book unique home dining experiences.', {
            demoUrl: 'https://potluck-ochre.vercel.app/',
            githubUrl: 'https://github.com/alfredang/potluck',
            techStack: ['Next.js', 'Vercel'],
            features: [
              'Chef discovery by cuisine type, location, ratings, and price range',
              'Real-time search and category filters',
              'Chef profile browsing',
              'Available dates and time slots selection',
              'Booking system with guest count',
              'Special dietary requirements input',
              'Detailed menus and reviews',
              'Chef ratings display',
              'Social media links on chef profiles',
              'Free tier subscription',
              'Pro tier ($19/mo) for chefs',
              'Unlimited tier ($49/mo) for chefs',
              'Singapore-based home chef marketplace',
              'Direct booking with chefs',
            ],
          }),
        ],
      },
      {
        label: 'Sports & Wellness',
        items: [
          makeProject('I Am Good', 'Personal safety check-in app for individuals living alone with one-tap check-ins, configurable schedules, and automatic alerts to emergency contacts.', {
            demoUrl: 'https://iamgood-psi.vercel.app/',
            githubUrl: 'https://github.com/alfredang/iamgood',
            techStack: ['Next.js', 'Vercel'],
            features: [
              'One-tap check-in button',
              'Health status tags (I\'m okay, I feel unwell, Need to talk)',
              'Emergency contact management (up to 5 contacts)',
              'Email, phone, and relationship information storage',
              'Flexible scheduling (daily, twice-daily, weekly, custom intervals)',
              'Configurable grace period (15 min to 2 hours)',
              'Automatic email alerts via Resend',
              'Check-in history with chronological organization',
              'PWA-ready for mobile installation',
              'Add to Home Screen capability',
              'Accessibility-first design',
              'Large touch targets (48px+)',
              'High contrast support',
              '18px base font size',
              'Designed for elderly users and non-technical individuals',
            ],
          }),
          makeProject('SquashPro', 'Squash match finder with court booking, opponent matching, Google OAuth, interactive maps, player ratings, and AI coaching tips.', {
            demoUrl: 'https://squashpro.vercel.app',
            githubUrl: 'https://github.com/alfredang/SquashPro',
            techStack: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS'],
            features: [
              'Court booking with interactive map',
              'Match discovery for finding open matches',
              'Join matches with other players',
              'Player profiles with ratings and skill levels',
              'Secure Google authentication',
              'AI coaching with Google Gemini',
              'Personalized coaching tips',
              'Live match updates via Supabase',
              'Live booking updates via Supabase',
              'React with TypeScript implementation',
              'Tailwind CSS styling',
            ],
          }),
        ],
      },
    ],
  },
  {
    title: 'Others',
    icon: HiPuzzlePiece,
    subcategories: [
      {
        label: 'Games',
        items: [
          makeProject('Futuristic Pong', 'Sleek, futuristic Pong game with neon aesthetics, adaptive AI difficulty, and real-time Web Audio synthesis.', {
            demoUrl: 'https://alfredang.github.io/pong-game/',
            githubUrl: 'https://github.com/alfredang/pong-game',
            techStack: ['Vite', 'Tailwind CSS', 'JavaScript', 'Web Audio API'],
            features: [
              'Three difficulty levels (Easy, Normal, Hard)',
              'Neon glow visual effects',
              'CRT scanlines aesthetic',
              'Glassmorphism UI elements',
              '60 FPS gameplay performance',
              'Real-time synthesized audio (no external files)',
              'Square wave clicks for paddle hits',
              'Sine wave effects for wall bounces',
              'Sawtooth sweeps for scoring events',
              'Mouse tracking for desktop',
              'Keyboard controls (W/S or arrow keys)',
              'Mobile touch-based paddle control',
              'Responsive design for multiple platforms',
              'Vanilla JavaScript, Vite, Tailwind CSS v4',
              'Less than 50kb gzipped file size',
            ],
          }),
          makeProject('Kid-Friendly Sudoku', 'Colorful 9x9 Sudoku game with three difficulty levels, countdown timer, and click-to-play number pad.', {
            demoUrl: 'https://alfredang.github.io/sudoku/',
            githubUrl: 'https://github.com/alfredang/sudoku',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              '3 difficulty levels (Easy, Medium, Hard)',
              'Countdown timer with color pulses',
              'Click-to-play controls without keyboard required',
              'Smart real-time validation with conflict highlighting',
              'Red highlighting for invalid entries',
              'Friendly error messages',
              'Puzzle completion detection',
              'Celebration animation on win',
              'Reveal solution functionality',
              'Color-coded number indicators (original vs. user vs. auto-revealed)',
              'Fully responsive design',
              'Desktop, tablet, and mobile support',
              'Vanilla JavaScript implementation',
            ],
          }),
          makeProject('Modern Frogger', 'Cute, modern remake of the classic Frogger game with smooth animations.', {
            demoUrl: 'https://alfredang.github.io/Frogger-game/',
            githubUrl: 'https://github.com/alfredang/Frogger-game',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              'Classic Frogger gameplay (dodge cars, hop on logs)',
              'Cute vector-style graphics with pastel colors',
              'Responsive design for desktop and tablet',
              'Audio feedback for jumps, collisions, and winning',
              'Score tracking system',
              'Lives tracking system',
              'Arrow keys or WASD controls',
              'Pause functionality (P key)',
              'Vanilla HTML, CSS, and JavaScript implementation',
            ],
          }),
          makeProject('Modern Snake', 'Modern Snake game with smooth animations, particle effects, and polished visuals.', {
            demoUrl: 'https://alfredang.github.io/snake-game/',
            githubUrl: 'https://github.com/alfredang/snake-game',
            techStack: ['HTML5', 'CSS3', 'JavaScript'],
            features: [
              'Animated apple with pulsing effect',
              'Realistic apple shape rendering',
              'Snake with expressive eyes, flickering tongue, and scale patterns',
              'Smooth 60fps animations',
              'Gradient shading and glow effects',
              'Particle effects when eating food',
              'High score persistence with localStorage',
              'Responsive controls (Arrow keys or WASD)',
              'Mobile-friendly design',
              'Vanilla JavaScript with HTML5 Canvas',
              'Dynamic visual feedback',
            ],
          }),
          makeProject('Neon Donkey Kong', 'Sleek, neon-inspired reimagining of the classic Donkey Kong arcade game.', {
            demoUrl: 'https://alfredang.github.io/donkey-kong-game/',
            githubUrl: 'https://github.com/alfredang/donkey-kong-game',
            techStack: ['HTML5 Canvas', 'JavaScript', 'Web Audio API'],
            features: [
              'Classic Donkey Kong gameplay mechanics',
              'Neon-inspired visual aesthetics',
              'Climb ladders and dodge rolling barrels',
              'HTML5 Canvas rendering',
              'Web Audio API for sound effects',
              'Responsive keyboard controls',
              'Score tracking system',
              'Retro arcade experience with modern styling',
              'Vanilla JavaScript implementation',
              'Browser-based gameplay',
            ],
          }),
          makeProject('Neon Pac-Man', 'Sleek, modern Neon Pac-Man arcade game with smart ghost AI, responsive design, and programmatic sound effects.', {
            demoUrl: 'https://alfredang.github.io/pacman-game/',
            githubUrl: 'https://github.com/alfredang/pacman-game',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              'Classic Pac-Man maze navigation',
              'Smart ghost AI with different behaviors',
              'Power pellets for ghost hunting',
              'Neon visual effects and glow',
              'Programmatic sound effects generation',
              'Score tracking with high score',
              'Lives system',
              'Level progression',
              'Responsive design for all devices',
              'Keyboard controls (Arrow keys)',
              'Vanilla JavaScript with HTML5 Canvas',
              'Retro arcade aesthetics with modern twist',
            ],
          }),
          makeProject('Neon Tetris', 'Modern, browser-based Tetris game with responsive design and neon arcade visuals.', {
            demoUrl: 'https://alfredang.github.io/tetris-game/',
            githubUrl: 'https://github.com/alfredang/tetris-game',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              'Classic Tetris gameplay with seven tetrominoes',
              'Neon-inspired visual design',
              'Smooth piece rotation and movement',
              'Line clearing mechanics',
              'Score tracking system',
              'Level progression with increasing speed',
              'Next piece preview',
              'Hold piece functionality',
              'Keyboard controls (Arrow keys, Space, C)',
              'Responsive layout for desktop and mobile',
              'Vanilla JavaScript implementation',
              'Modern UI with glowing effects',
            ],
          }),
          makeProject('Pastel Space Invaders', 'Whimsical, pastel-themed reimagining of Space Invaders with smooth animations.', {
            demoUrl: 'https://alfredang.github.io/space-invader-game/',
            githubUrl: 'https://github.com/alfredang/space-invader-game',
            techStack: ['HTML5', 'JavaScript'],
            features: [
              'Classic Space Invaders gameplay',
              'Pastel color scheme with soft aesthetics',
              'Smooth animations and movement',
              'Alien formations with wave patterns',
              'Player spaceship controls',
              'Shooting mechanics',
              'Defensive barriers',
              'Score tracking',
              'Lives system',
              'Increasing difficulty levels',
              'Keyboard controls (Arrow keys, Space)',
              'HTML5 Canvas rendering',
              'Retro arcade feel with modern visuals',
            ],
          }),
          makeProject('Pixel Art Dungeon Crawler', 'Top-down pixel art dungeon crawler with elemental spells and 4 dungeon rooms.', {
            demoUrl: 'https://alfredang.github.io/pixelartgame/',
            githubUrl: 'https://github.com/alfredang/pixelartgame',
            techStack: ['HTML5 Canvas', 'JavaScript'],
            features: [
              'Top-down dungeon exploration',
              'Pixel art graphics and animations',
              '4 unique dungeon rooms to explore',
              'Elemental spell casting system',
              'Fight haunted weapons and enemies',
              'Player character movement controls',
              'Combat mechanics with spell selection',
              'Room-to-room navigation',
              'Health tracking system',
              'WASD or Arrow key controls',
              'HTML5 Canvas rendering',
              'Retro pixel art aesthetic',
              'Vanilla JavaScript game engine',
            ],
          }),
          makeProject('Retro Street Fighter', '2D fighter with original pixel-art assets, custom animation engine, and smooth local PvP gameplay.', {
            demoUrl: 'https://alfredang.github.io/street-fighter-game/',
            githubUrl: 'https://github.com/alfredang/street-fighter-game',
            techStack: ['HTML5 Canvas', 'JavaScript'],
            features: [
              '2D fighting game mechanics',
              'Original pixel-art character sprites',
              'Custom animation engine for smooth movements',
              'Local Player vs Player (PvP) mode',
              'Fighting moves and combos',
              'Health bar tracking',
              'Special attack animations',
              'Character selection',
              'Dual player controls (Player 1: WASD+keys, Player 2: Arrow+keys)',
              'Hit detection system',
              'Round-based combat',
              'HTML5 Canvas rendering',
              'Retro arcade fighting experience',
            ],
          }),
          makeProject('Story Creator (AutoGen + Chainlit)', 'Multi-agent interactive story creator with human-in-the-loop review using AutoGen and Chainlit.', {
            demoUrl: 'https://web-production-fba33.up.railway.app/',
            githubUrl: 'https://github.com/alfredang/story-creator-autogen-chainlit',
            techStack: ['Python', 'AutoGen', 'Chainlit', 'Railway'],
            features: [
              'Multi-agent story generation system',
              'Human-in-the-loop review process',
              'Interactive chat interface via Chainlit',
              'Microsoft AutoGen framework integration',
              'AI-powered creative writing',
              'Real-time story collaboration',
              'User input for story direction',
              'Agent orchestration for story development',
              'Review and refinement workflow',
              'Railway deployment for accessibility',
              'Python backend with async support',
              'Conversational story creation experience',
            ],
          }),
          makeProject('Tic-Tac-Toe AI', 'Sleek Tic-Tac-Toe game with unbeatable Minimax AI opponent, dark-mode UI, and smooth animations.', {
            demoUrl: 'https://alfredang.github.io/tic-tac-toe-game/',
            githubUrl: 'https://github.com/alfredang/tic-tac-toe-game',
            techStack: ['HTML', 'CSS', 'JavaScript'],
            features: [
              'Unbeatable Minimax AI algorithm',
              'Player vs AI mode',
              'Player vs Player mode',
              'Dark mode UI design',
              'Smooth CSS animations',
              'Win detection algorithm',
              'Draw/tie game handling',
              'Game state tracking',
              'Reset game functionality',
              'Responsive grid layout',
              'Hover effects and visual feedback',
              'Modern minimalist design',
              'Vanilla JavaScript implementation',
            ],
          }),
        ],
      },
    ],
  },
]

// Flat list of all projects for routing
export const ALL_PROJECTS = PORTFOLIO_CATEGORIES.flatMap((cat) =>
  cat.subcategories.flatMap((sub) =>
    sub.items.map((item) => ({
      ...item,
      category: cat.title,
      categoryIcon: cat.icon,
      subcategory: sub.label,
    }))
  )
)
